# -*- coding: utf-8 -*-
"""leaf_colour_tourch_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezUxo83329BlcToXJYLemygPXXgRZyzW
"""
import torch
import torchvision
from torchvision import transforms as T
from PIL import Image
import cv2

device = torch.device('cpu')
model = torch.load("/image_processing/mask_r_cnn/models/model_4.pth", map_location=device)
model.eval()

img = Image.open("/image_processing/mask_r_cnn/test/b.jpg")
transform = T.ToTensor()
ig = transform(img)
with torch.no_grad():
    pred = model([ig.to(device)])

masks = pred[0]["masks"]
mask = masks[0 , 0]
mask = masks[0 , 0] > 0.5
m = mask.cpu().detach().numpy().astype("uint8") * 255
cv2.imshow(m)

igg = cv2.imread("/image_processing/mask_r_cnn/test/b.jpg")
fin_img = cv2.bitwise_and(igg , igg , mask = m)
cv2.imshow(fin_img)

